# 03 Time-Series Analysis
Inspect coverage, measurement intervals, and temporal plots. Seasonal or weekly claims require sufficient observed coverage.

In [8]:

from src.data_preprocessing import load_data
from src.time_series_analysis import measurement_intervals

df = load_data("data/processed/water_quality_clean.csv")

intervals = measurement_intervals(df)
intervals.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118286 entries, 0 to 118285
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            118286 non-null  int64
 1   created_date  118286 non-null  datetime64[ns]
 2   water_pH      118286 non-null  float64
 3   TDS           118286 non-null  int64
 4   water_temp    118286 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 4.5 MB
None

count                       118285
mean     0 days 00:00:40.371475673
std      0 days 00:50:07.114253570
min                0 days 00:00:00
25%                0 days 00:00:00
50%                0 days 00:00:00
75%                0 days 00:00:00
max                7 days 12:18:00
Name: created_date, dtype: object

In [10]:
from src.feature_engineering import create_time_features

df_features = create_time_features(df)
df_features.head()

,id,created_date,water_pH,TDS,water_temp,hour,day,day_of_week,month
0,181775,2023-01-26 11:24:00,7.60,250,24.00,11,26,3,1
1,181777,2023-01-26 11:33:00,7.60,247,24.06,11,26,3,1
2,181778,2023-01-26 12:02:00,7.60,249,24.19,12,26,3,1
3,181780,2023-01-26 12:05:00,6.92,247,24.19,12,26,3,1
4,181782,2023-01-26 12:10:00,7.30,245,24.25,12,26,3,1

In [12]:
from src.feature_engineering import create_lag_features

df_features_lag = create_lag_features(
    df_features,
    lags=(1, 3, 6),
)
df_features_lag.head()

,id,created_date,water_pH,TDS,water_temp,hour,day,day_of_week,month,pH_lag_1,pH_lag_3,pH_lag_6,TDS_lag_1,TDS_lag_3,TDS_lag_6,temperature_lag_1,temperature_lag_3,temperature_lag_6
0,181775,2023-01-26 11:24:00,7.60,250,24.00,11,26,3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,181777,2023-01-26 11:33:00,7.60,247,24.06,11,26,3,1,7.60,NaN,NaN,250.0,NaN,NaN,24.00,NaN,NaN
2,181778,2023-01-26 12:02:00,7.60,249,24.19,12,26,3,1,7.60,NaN,NaN,247.0,NaN,NaN,24.06,NaN,NaN
3,181780,2023-01-26 12:05:00,6.92,247,24.19,12,26,3,1,7.60,7.6,NaN,249.0,250.0,NaN,24.19,24.00,NaN
4,181782,2023-01-26 12:10:00,7.30,245,24.25,12,26,3,1,6.92,7.6,NaN,247.0,247.0,NaN,24.19,24.06,NaN

In [13]:
from src.feature_engineering import create_rolling_features

df_features_roll = create_rolling_features(
    df_features,
    window=3,
)

df_features_roll.head()

,id,created_date,water_pH,TDS,water_temp,hour,day,day_of_week,month,pH_lag_1,...,water_pH_rolling_min_3,water_pH_rolling_max_3,TDS_rolling_mean_3,TDS_rolling_std_3,TDS_rolling_min_3,TDS_rolling_max_3,water_temp_rolling_mean_3,water_temp_rolling_std_3,water_temp_rolling_min_3,water_temp_rolling_max_3
0,181775,2023-01-26 11:24:00,7.60,250,24.00,11,26,3,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,181777,2023-01-26 11:33:00,7.60,247,24.06,11,26,3,1,7.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,181778,2023-01-26 12:02:00,7.60,249,24.19,12,26,3,1,7.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,181780,2023-01-26 12:05:00,6.92,247,24.19,12,26,3,1,7.60,...,7.60,7.6,248.666667,1.527525,247.0,250.0,24.083333,0.097125,24.00,24.19
4,181782,2023-01-26 12:10:00,7.30,245,24.25,12,26,3,1,6.92,...,6.92,7.6,247.666667,1.154701,247.0,249.0,24.146667,0.075056,24.06,24.19

In [14]:
from src.feature_engineering import build_features

df_features = build_features(
    df,
    lags=(1, 3, 6),
    rolling_window=3,
)

df_features.head()

,id,created_date,water_pH,TDS,water_temp,hour,day,day_of_week,month,pH_lag_1,...,water_pH_rolling_min_3,water_pH_rolling_max_3,TDS_rolling_mean_3,TDS_rolling_std_3,TDS_rolling_min_3,TDS_rolling_max_3,water_temp_rolling_mean_3,water_temp_rolling_std_3,water_temp_rolling_min_3,water_temp_rolling_max_3
0,181775,2023-01-26 11:24:00,7.60,250,24.00,11,26,3,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,181777,2023-01-26 11:33:00,7.60,247,24.06,11,26,3,1,7.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,181778,2023-01-26 12:02:00,7.60,249,24.19,12,26,3,1,7.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,181780,2023-01-26 12:05:00,6.92,247,24.19,12,26,3,1,7.60,...,7.60,7.6,248.666667,1.527525,247.0,250.0,24.083333,0.097125,24.00,24.19
4,181782,2023-01-26 12:10:00,7.30,245,24.25,12,26,3,1,6.92,...,6.92,7.6,247.666667,1.154701,247.0,249.0,24.146667,0.075056,24.06,24.19

In [15]:
df_features.isna().sum()

id                           0
created_date                 0
water_pH                     0
TDS                          0
water_temp                   0
hour                         0
day                          0
day_of_week                  0
month                        0
pH_lag_1                     1
pH_lag_3                     3
pH_lag_6                     6
TDS_lag_1                    1
TDS_lag_3                    3
TDS_lag_6                    6
temperature_lag_1            1
temperature_lag_3            3
temperature_lag_6            6
water_pH_rolling_mean_3      3
water_pH_rolling_std_3       3
water_pH_rolling_min_3       3
water_pH_rolling_max_3       3
TDS_rolling_mean_3           3
TDS_rolling_std_3            3
TDS_rolling_min_3            3
TDS_rolling_max_3            3
water_temp_rolling_mean_3    3
water_temp_rolling_std_3     3
water_temp_rolling_min_3     3
water_temp_rolling_max_3     3
dtype: int64

In [19]:
from src.visualization import plot_time_series_summary

for column in ["water_pH", "TDS", "water_temp"]:
    plot_time_series_summary(
        df,
        column=column,
        path=f"../results/figures/time_series_summary_{column}.png",
        frequency="D",
    )